### ISSUE TITLE
Add source tarball

### ISSUE THREAD

**Issue by MayeulC** [flathub/io.github.yairm210.unciv#3]
As mentioned in the [main thread](https://github.com/flathub/flathub/pull/1339), we should add the source tarball here:

https://github.com/flathub/io.github.yairm210.unciv/blob/02f678c097ea7aaf7ea6e3feb0bff6602ab421b5/io.github.yairm210.unciv.yaml#L42

It later gets exported to separate extension and can be inspected by users.

_Originally posted by @barthalion in https://github.com/flathub/flathub/pull/1339#r378121913_

**Comment by TuxKruger** [comment]
Why is it a requirement though? Since the the metadata is pulling the JAR built by the original Maintainer from GitHub releases, I don't think it is needed. And I don't understand what @barthalion meant by "It later gets exported to separate extension". Can anyone explain it to me, I am new to this stuff.

**Comment by barthalion** [comment]
It's not a requirement, just something nice to have. Technically, GPL requires us to distribute source code, but not sure if it's true about MPL.

**Comment by TuxKruger** [comment]
So I read the license [here](https://www.mozilla.org/en-US/MPL/2.0/). It seems like we have to either provide the source code or any method to obtain a copy of it. 

so should we add tarball or add the link to the GitHub repo of Unciv for obtaining the source code in README.md?

**Comment by barthalion** [comment]
Looks like the appdata already links to GitHub repo so it can be closed then.
